#!/bin/bash
printf '%o\n' $((5#$(printf '%s' "$WATER" | tr '[:upper:]' '[:lower:]' | tr -cd 'water' | tr 'water' '01234') + 4#$(printf '%s' "$STIR" | tr '[:upper:]' '[:lower:]' | tr -cd 'stir' | tr 'stir' '0123'))) | tr '01234567' 'bestchol'
